### ISSUE TITLE
Aplicar acrescimo de info na optim.jurisdiction

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#11]
Algumas decisões sobre escolha de grade dependem de parâmetros métricos da geometria da jurisdição, e estes podem ficar em cache (`info`), tanto para reuso nesses cálculos como por seu valor informativo para o usuário final.

As grandezas relevantes são descritas pelos comments (ver com `\d+` no pgsql):

Column     |       Type        | Storage  |                              Description                               
-------------------|------------------|--------------|------------------------------------------------------
 area_km2       | integer               | plain    |  Area in square quilometers.
 area_sr        | double precision |       plain    | Area in spheroradians.
 side_estim_km  | double precision |          plain    | Estimating the side size of an equivalent-area square, in quilometers.
 side_estim_deg | double precision |         plain    | Estimating the side size of an equivalent-area square, in degrees.
 fat_deg_m      | numeric   |main     | Average degree per meter convertion factor at the points of this area.
 elongation_factor      | numeric   |main     | Factor between sides of an estimated rectangular box fitting the simplified geometry.

### Implementação

O script abaixo precisa ser incluso nos procedimentos padrão de ingestão.

```sql
DROP VIEW IF EXISTS optim.vw03prepare_jurisdiction_metrics1;
CREATE VIEW optim.vw03prepare_jurisdiction_metrics1 AS
 SELECT osm_id, isolabel_ext,   round(area_m/1000000.0)::int as area_km2,
       round( area_sr, 5)::float as area_sr,
       round( SQRT(area_m)/1000.0, 1)::float as side_estim_km,
       round( SQRT(area_sr), 4)::float       as side_estim_deg,
       round( SQRT(area_sr)/SQRT(area_m), 7 ) as fat_deg_m
 FROM (
   SELECT *, st_area(geom,true) area_m,
                 st_area(geom) area_sr
   FROM optim.vw01full_jurisdiction_geom
   WHERE geom IS NOT NULL
 ) t0
;
comment on view optim.vw03prepare_jurisdiction_metrics1 IS 'Prepare the standard geometry metrics.';
comment on column optim.vw03prepare_jurisdiction_metrics1.area_sr IS 'Area in spheroradians.';
comment on column optim.vw03prepare_jurisdiction_metrics1.side_estim_km IS 'Estimating the side size of an equivalent-area square, in quilometers.';
comment on column optim.vw03prepare_jurisdiction_metrics1.side_estim_deg IS 'Estimating the side size of an equivalent-area square, in degrees.';
comment on column optim.vw03prepare_jurisdiction_metrics1.fat_deg_m IS 'Average degree per meter convertion factor at the points of this area.';

-- Perigo!
UPDATE  optim.jurisdiction
SET info = COALESCE (info,'{}'::JSONB) || (to_jsonb(t) - 'osm_id')
FROM   ( 
  SELECT osm_id, area_km2, area_sr, side_estim_km, side_estim_deg, fat_deg_m
   FROM optim.vw03prepare_jurisdiction_metrics1 
) t
WHERE t.osm_id=jurisdiction.osm_id
;  -- UPDATE 7133
```

### Shape sizes
Tradicionalmente usamos uma "BBOX livre" (independente grade ou do sistema de coordenadas) para avaliar se a box será mais quadrada ou retangular. Todavia a BBOX será muito sensivel a geometrias  "com braços" ou pequenos trechos alingados, não-representativos da área total do polígono. Um forma menos sensível de estimar o tamanho dos lados de um retângulo de área equivalente é através da função  *shapedescr_sizes*, definida em https://gist.github.com/ppKrauss/3810651

As aplicações são diveras, por exemplo para avaliar o formato de quadras retangulares, ou estimar o grau de "alongamento" de polígonos em geral, Nos algoritmos de grade usaremos o *fator de alongamento* como recurso para decidir se a jurisdição precisa ou não fazer uso de gecódigos indexados.

```sql
DROP VIEW IF EXISTS optim.vw04prepare_jurisdiction_shapemetrics;
CREATE VIEW optim.vw04prepare_jurisdiction_shapemetrics AS
SELECT *, round( (rectang_factor_deg + 1.5*elongation_factor_deg)/2.5 , 2)::float AS elong_deg_mixfactor
FROM (
 SELECT osm_id, isolabel_ext,
       round(s[1]/fat_deg_m)/1000 as rectang_L_km,
       round(s[2]/fat_deg_m)/1000 as rectang_H_km,
       CASE 
          WHEN s[6]=0 THEN (round( ((s[1]-s[2])/side_estim_deg)/fat_deg_m )/1000.0)::int
          ELSE -1
       END AS elongation_factor_km,
      CASE
          WHEN s[6]=0 THEN round( (s[1]-s[2]) / side_estim_deg , 2)::float
          ELSE -1
       END AS elongation_factor_deg,
      round( 0.95 + (diaglen_deg - side_estim_deg)/side_estim_deg , 3)::float as rectang_factor_deg
 FROM (
   SELECT  *, (info->'side_estim_deg')::float AS side_estim_deg,
            (info->'side_estim_km')::float  AS side_estim_km,
             (info->'fat_deg_m')::float AS fat_deg_m,
             shapedescr_sizes( ST_SimplifyPreserveTopology(geom, (info->'side_estim_deg')::float/350.0) ) AS s,
                   -- ideal usar ao inves de side_estim a media (diaglen_deg+side_estim_deg)/2.0 
             ST_Length( ST_BoundingDiagonal(geom,true) ) as diaglen_deg
  FROM optim.vw01full_jurisdiction_geom
  WHERE geom is not null  AND info?'side_estim_deg'
 ) t1
) t2;

-- check:
SELECT percentile_disc( array[0.2, 0.5, 0.8] ) WITHIN GROUP (ORDER BY elongation_factor_deg) as pctl_elongation_factor_deg ,
       percentile_disc( array[0.2, 0.5, 0.8] ) WITHIN GROUP (ORDER BY rectang_factor_deg) as pctl_rectang_factor_deg,
       percentile_disc( array[0.2, 0.5, 0.8] ) WITHIN GROUP (ORDER BY elong_deg_mixfactor) as pctl_mix
FROM optim.vw04prepare_jurisdiction_shapemetrics
WHERE isolabel_ext LIKE 'CO-%-%' AND  elongation_factor_deg>0
;  --  shape={1.5,2.02,2.63}      |    pctl_rectang={1.858,2.017,2.255}     |   pctl_mix={1.65,2.02,2.47}
-- Estamos adotando o mix, deu mais certo.

----- Perigo!
UPDATE  optim.jurisdiction
SET info = COALESCE (info,'{}'::JSONB) || jsonb_build_object('elongation_factor',t.elong_deg_mixfactor)
FROM  optim.vw04prepare_jurisdiction_shapemetrics t
WHERE t.osm_id=jurisdiction.osm_id  AND t.elongation_factor_deg>0
;  -- UPDATE 7115
```

**Sugestão a testar:** 

* Encaixar jurisdições pequenas na grade sempre que `(info->'elongation_factor')::float < 1.7`
* Usar geocódigo indexado nas jurisdições com `(info->'elongation_factor')::float >=2.5`, exceto se for muito pequena
* Nas demais avaliar melhor qual o caso (indexar ou encaixar). Talvez visulizando no QGIS com o seu nome ou ID, e colorindo com elongation_factor.

------

![image](https://user-images.githubusercontent.com/1651447/175841183-421f9995-3546-445b-9162-88e37de8fb8c.png)

![image](https://user-images.githubusercontent.com/1651447/175840404-dbc80cd4-3946-4210-b08f-45a7db022b7b.png)

![image](https://user-images.githubusercontent.com/1651447/175841360-6b5390a5-5b05-451a-a924-f07ce37ea6ef.png)

![image](https://user-images.githubusercontent.com/1651447/175841480-22d9a6c2-4c8d-4096-b110-ad4369d43916.png)

**Comment by ppKrauss** [comment]
Usando elongation_factor para obter boas amostragens para teste de cobertura, ver https://github.com/osm-codes/WS/blob/main/src/country_sample_function.sql   Exemplo:  `select * from osmc_country_sample('CO');`. Falta ajustar ao schema optim, hoje na base *dl03t_main*. 

citype    |      isolabel_ext       |  osm_id  | side  | elongfact 
--------------|-------------------------|----------|------|-----------
peq-nonalong | [CO-ANT-Sabaneta](https://osm.codes/CO-ANT-Sabaneta)         |  [1307270](https://osm.org/relation/1307270) |   3.9 |      1.14
 peq-nonalong | CO-RIS-Virginia         |  1348326 |   5.7 |      1.58
 peq-nonalong | CO-BOY-Iza              |  1315386 |   5.9 |      1.54
 peq-nonalong | CO-QUI-Buenavista       |  1347532 |   6.1 |      1.24
 peq-nonalong | CO-ANT-Estrella         |  1307284 |   6.2 |      1.53
 peq-nonalong | CO-ATL-Sabanagrande     |  1341558 |   6.4 |      1.32
 peq-along    | CO-NAR-Providencia      | 11894047 |   6.4 |      2.61
 peq-along    | CO-VAC-Ulloa            |  1311763 |   6.5 |      3.64
 peq-along    | CO-NSA-PuertoSantander  | 11896145 |   6.7 |      2.95
 peq-along    | CO-SAN-California       |  1343387 |   6.7 |      2.74
 peq-along    | CO-NAR-Aldana           | 11333702 |   6.8 |      2.74
 peq-along    | CO-CUN-Alban            |  1355693 |   7.3 |       2.8
 gr-nonalong  | CO-VAU-Mitu             | 11382140 |   127 |      1.67
 gr-nonalong  | CO-CAU-Guapi            |  1310021 |  50.6 |      1.36
 gr-nonalong  | CO-TOL-Rioblanco        |  1308614 |  45.2 |      1.63
 gr-nonalong  | CO-COR-Ayapel           |  1343439 |  43.9 |      1.61
 gr-nonalong  | CO-LAG-Dibulla          |  1314633 |  41.9 |      1.55
 gr-nonalong  | CO-CHO-SanJosePalmar    |  1343038 |  39.7 |      1.26
 gr-along     | CO-CAQ-Solano           |  1342101 | 205.3 |      3.39
 gr-along     | CO-CAQ-SanVicenteCaguan |  1342095 | 132.8 |      2.73
 gr-along     | CO-GUV-SanJoseGuaviare  | 11378346 | 129.4 |      4.19
 gr-along     | CO-GUA-Inirida          |  2346720 | 125.9 |      2.62
 gr-along     | CO-GUA-Barrancominas    | 11334013 | 119.9 |      3.23
 gr-along     | CO-AMA-PuertoArica      |  1335190 | 116.7 |      2.69
 big          | CO-VID-Cumaribo         | 11319781 | 255.3 |      2.45
 big          | CO-VID-Primavera        | 11319669 | 132.7 |      1.95
 big          | CO-MET-PuertoCarreno    | 11371824 | 131.3 |      1.81
 small        | CO-SAN-Palmar           |  1423515 |   4.5 |      2.24
 small        | CO-ANT-Itagui           |  1343279 |   4.5 |      1.81
 small        | CO-BOY-Busbanza         |  1315385 |   5.2 |      1.62

**Comment by 0e1** [comment]
As views citadas na issue foram adicionadas em [optim-step6-metrics](https://github.com/digital-guard/preserv/blob/main/src/optim-step6-metrics.sql).

Os updates devem ser realizados sempre que novas geometrias forem adicionadas na tabela de jurisdições.

Em [man-updateJurisd](https://github.com/digital-guard/preserv/blob/main/docs/pt/man-updateJurisd.md) estão os passos para trabalhar em [optim.jurisdiction](https://github.com/digital-guard/preserv/blob/main/src/optim-step1-ini.sql#L9) e [optim.jurisdiction_geom](https://github.com/digital-guard/preserv/blob/main/src/optim-step1-ini.sql#L52).

Issues associadas: https://github.com/osm-codes/WS/issues/37, https://github.com/digital-guard/preserv/issues/116
