### ISSUE TITLE
Correções menores na interface de teste

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#13]
Nesta issue listar na forma de checklist as pendências que vão sendo resolvidas conforme possível
- [x] checkboxes para remover "pin icons"
- [x] checkboxes para remover rótulos 
- [x] Resolver problemas de zoom inicial: usar o fit geojson somando ou subtraindo um (ou mais) para não ficar tão perto.
- [x] Resolver problemas de zoom máximo: existem plugins para manter uma "versão pixelizada" do fundo no zoom maior.
- [x]  jurisdições em vermelho

**Comment by 0e1** [comment]
- Marcadores agora são agrupados em _layers_ e desabilitados por _default_;
- Botão permite mostrar/esconder os rótulos. Se escondidos, passar o mouse sobre a área da caixa exibe o marcador;
- Jurisdições são exibidas em vermelho;
- Foi adicionada a propriedade _maxNativeZoom_ na definição dos _L.tileLayer_. Assim, em zoom maiores que ele, os tiles ficam pixelados. Também é exibido o zoom atual, na parte inferior da interface;
- Foram adicionados 2 checkbox para  _fit_. Um para os limites da geometria, que altera o nível de zoom, desabilitado por default. E outro, para o centro da geometria, sem alterar o nível de zoom, habilitado por _default_.
