### ISSUE TITLE
Correções e adaptações na interface de teste

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#16]
(aguardar juntar mais requisitos)

1. Ampliar as opções de base: além de base32 e base16h, incluir base16 (pura) e base16h-int (só níves inteiros).<br/> ![image](https://user-images.githubusercontent.com/1651447/178539818-6e405c65-de62-4bd6-b9f3-2d77c4f4440f.png)
2. Caixa de texto (HTML `textarea`) para acumular todos os geocódigos solicitados, ou cobertura solicitada pela URL.

-----

PS: esta issue é continuação de #13

**Comment by 0e1** [comment]
Item 2 atendido. 
Exemplos de acesso por uri:
http://osm.codes/BR-1,2,3,4/list
http://osm.codes/CO-1,2,3,4.json/list

**Comment by 0e1** [comment]
Item 1 resolvido por:

https://github.com/osm-codes/gridMap-draftPages/commit/1faf71df91364355aa10bd84f8cf0f21c882ce19
https://github.com/osm-codes/gridMap-draftPages/commit/0282dfe4372373e78ad43c21f523e3b87f8d2b8c
https://github.com/osm-codes/gridMap-draftPages/commit/4e6a5c9f0b9c6ba279efb955ea9d28562313beab

**Comment by ppKrauss** [comment]
> Exemplos de acesso por uri:
> http://osm.codes/BR-1,2,3,4/list
> http://osm.codes/CO-1,2,3,4.json/list

Nada funciona: não importa. O importante de lembrar aqui é que temos muita coisa, porém nada documentado, portanto tudo será esquecido se não documentar.
