### ISSUE TITLE
Interface de grade com opção de apresentar coberturas municipais e L0 com seu recorte

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#18]
No banco de dados são armazenadas as geometrias resultantes da intersecção, então não há custo maior em se devolver ao usuário a geometria correta da cobertura nominal, tal qual fazemos uso na discriminação.

**Comment by 0e1** [comment]
Implementado, usar _checkbox_ ao lado do botão _jurisdiction_.
![Captura de tela de 2022-07-28 14-23-34](https://user-images.githubusercontent.com/41844788/181599666-176cf9f1-1c5d-4d73-bdab-42b0236c9076.png)
