### ISSUE TITLE
Interface de grade com opção de mostrar subgrade com pontos

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#19]
Pontos pink bem destacados e sem confusão com o "pin do click".  A "grade de pontos" auxilia na decisão de atribuição de endereço.

**Comment by 0e1** [comment]
Em funcionamento.
![Captura de tela de 2022-07-28 14-05-28](https://user-images.githubusercontent.com/41844788/181598750-f0915460-78cd-455d-9186-29727fa54965.png)
