### ISSUE TITLE
Revisar e refatorar osm_city

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#2]
A tabela `osm_city` da base DL03t_main pode ser renomeada para `optim.jurisdiction_geom` para integrar os cores A4A  e OSMC.

Agora possui tanto cidades como países (dados da tabela countries do Natural Earth).

**Comment by ppKrauss** [comment]
@0e1

**Comment by 0e1** [comment]
Considero isso feito.

**Comment by 0e1** [comment]
Lembrete: _precisa conferir se teve reflexo na documentação ... Documentar o complemento: em uma outra tabela (a de-para) existe uma extensão OsmCodes (convenção ainda arbitrária já que não é oficial do país) para isoLabel_ext, que são os quadrantes da cidade, C, N, S, etc.  Em muitos casos vamos incluir esse 4o nivel de jurisdição isoLabel_
