### ISSUE TITLE
Abordagem para a interface final de códigos postais

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#22]
A finalidade principal dos geocódigos curtos é suprir a demanda nacional por códigos postais eficientes. A grade base32 em si não é um objetivo, inclusive a recomendação para uso científico e a base 16h. 

Em ambos os casos, código postal e científico, o foco não é o desenho ou navegação arbirários, mas o uso de um contexto como ponto de partida: a interface de [generalized-geohash explorer](https://geohash.softeng.co/) **não precisa partir do globo**, mas sim de um país ou um prefixo dentro de um país.

**O prefixo e o tipo de geocódigo (postal ou científico) é que estabelecem a interface**, antes do usuário definir o prefixo não faz sentido mostrar algo, ele precisa escolher o que quer... E sempre será contextual. Todas **as interfaces precisam ser orientadas ao contexto** e não ao globo.

**Comment by ppKrauss** [comment]
Temos outra issue em algum lugar reforçando isso. Linkar.

## Corrigir bug

Não pode mais mostrar geocódigo de grade base32, é para mostrar apenas o **geocódigo postal**, ou seja, no exemplo, apenas

```
Postal code: 1H
Area: 524288 m2
Side: 724.08 m
Jurisdiction: UY-CO-ColoniaSacramento
```
Acrescentar tags `<b>`  e `<big>`  no postal code. A jurisdiction com small.

![image](https://user-images.githubusercontent.com/1651447/190012325-80174cda-d85b-45b8-a1fd-b404c5be6fe7.png)

**Comment by 0e1** [comment]
Acredito que o assunto já foi contemplado. Atualmente o contexto é utilizado no processo de encode/decode e nas interfaces. Também, já está sendo exibido apenas o código postal.
