### ISSUE TITLE
Mar territorial na cobertura L0

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#25]
Na interface e nos recortes se faz necessária a adição do mar territorial. O polígono do "jurisdição marítima" pode ser obtido da subtração da jurisdição completa pela jurisdição continental. É importante que **os polígonos recortados da grade *L0* façam uso desse recorte**. Sem isso a representação da grade recortada ainda estará errada (bug). 

Exemplo na Colômbia:

![image](https://user-images.githubusercontent.com/1651447/180627302-285cb544-084a-4ed0-80ec-0ef6aebcb805.png)

NOTA: em geral o mar territorial está sob jurisdição da Marinha, portanto seria federal... Mas cada país pode ter a sua norma e resultar em jurisdições municipais de mar territorial. **Em caso de jurisdição federal não deve entrar no código postal (que é inerentente municipal), apenas na grade completa.

**Comment by 0e1** [comment]
Atualmente, a origem dos dados é:

1. municípios, estados ou equivalentes: https://openstreetmap.org
2. países: https://naturalearthdata.com

Observações:
- 2 é mais grosseira que a união de 1;
- 2 não inclui o mar territorial;
- 2 é mais grosseira que as geometrias de países oriundas do OSM;
- O mar territorial faz parte da geometria do paíse no OSM, exemplo: https://www.openstreetmap.org/relation/120027.

Então:
1. Abandonar o uso de 2, na América do Sul;
2. Usar geometria dos países oriunda do OSM;
3. Obter a geometria do país sem o mar territorial a partir da união dos estados ou municípios;
4. Evitar intersecção não nulas entre países fronteiriços extraindo os dados de um mesmo arquivo da América do Sul.

**Comment by 0e1** [comment]
Foram importadas as geometrias do extrato da América do Sul disponibilizado pela Geofabrik. Esses geometrias incluem o mar territorial do país.

Alguns detalhes:
- Foram atualizadas as geometrias de todos os países na América do Sul, com geometrias oriundas do OSM/Geofabrik;
- Geometrias de municípios (ou equivalente) não possuem mar territorial;
- Geometrias de estados (ou equivalente) não possuem mar territorial, exceto Brasil e Suriname;
- Quando necessário, podemos gerar a geometria do país sem mar territorial, usando a geometria dos municipios.



![Captura de tela de 2022-07-28 13-52-10](https://user-images.githubusercontent.com/41844788/181594749-84618557-5071-4f45-b29c-b6abf4b07abf.png)
![Captura de tela de 2022-07-28 13-51-32](https://user-images.githubusercontent.com/41844788/181594756-ed5cc9a2-f952-477f-aaeb-91264496b341.png)
