### ISSUE TITLE
Exportação de todos os dados ineditos com endereço

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#26]
Pontos e lotes com pelo menos um, nome de rua e/ou numeração predial, distinguindo dados inéditos de não-inéditos, e exportando para shapfile

**Comment by luisfelipebr** [comment]
@0e1

Inéditos:

- Contagem
- Governador Valadares

Não inéditos:

- São Bernardo do Campo 
- Guarulhos
- Rio de Janeiro
- Pinhais

**Comment by 0e1** [comment]
Gerar apenas para os inéditos? Ou para os não inéditos também?

**Comment by luisfelipebr** [comment]
Dados inéditos:
[BR-AC-RioBranco/pk0042.01](http://addressforall.org/teste2/br-ac-riobranco_pk0042.01_block.html)
[BR-MG-Contagem/pk0009.01](http://addressforall.org/teste2/br-mg-contagem_pk0009.01_block.html)
[BR-MG-GovernadorValadares/pk0039.01](http://addressforall.org/teste2/br-mg-governadorvaladares_pk0039.01_block.html)
[BR-MS-CampoGrande/pk0034.01](http://addressforall.org/teste2/br-ms-campogrande_pk0034.01_nsvia.html)
[BR-PR-Araucaria/pk0061.01](http://addressforall.org/teste2/br-pr-araucaria_pk0061.01_nsvia.html)
[BR-PR-Maringa/pk0110.01](http://addressforall.org/teste2/br-pr-maringa_pk0110.01_geoaddress.html)
[BR-RS-PortoAlegre/pk0018.01](http://addressforall.org/teste2/br-rs-portoalegre_pk0018.01_geoaddress.html)
[BR-SP-Itu/pk0024.01](http://addressforall.org/teste2/br-sp-itu_pk0024.01_block.html)
[BR-SP-Osasco/pk0028.01](http://addressforall.org/teste2/br-sp-osasco_pk0028.01_block.html)
[BR-SP-RibeiraoPreto/pk0052.01](http://addressforall.org/teste2/br-sp-ribeiraopreto_pk0052.01_block.html)
[BR-SP-Santos/pk0029.01](http://addressforall.org/teste2/br-sp-santos_pk0029.01_geoaddress.html)
[BR-SP-SaoVicente/pk0032.01](http://addressforall.org/teste2/br-sp-saovicente_pk0032.01_geoaddress.html)
[BR-SP-Sorocaba/pk0031.01](http://addressforall.org/teste2/br-sp-sorocaba_pk0031.01_parcel.html)

Download inédito (disponível para visualização online):
[BR-RS-Gravatai/pk0017.01](http://addressforall.org/teste2/br-rs-gravatai_pk0017.01_nsvia.html)
[BR-RS-Pelotas/pk0080.01](http://addressforall.org/teste2/br-rs-pelotas_pk0080.01_geoaddress.html)
[BR-RS-SantaMaria/pk0019.01](http://addressforall.org/teste2/br-rs-santamaria_pk0019.01_block.html)

Não inéditos:
[BR-ES-VilaVelha/pk0007.01](http://addressforall.org/teste2/br-es-vilavelha_pk0007.01_block.html)
[BR-GO-Goiania/pk0054.01](http://addressforall.org/teste2/br-go-goiania_pk0054.01_block.html)
[BR-MG-BeloHorizonte/pk0008.01](http://addressforall.org/teste2/br-mg-belohorizonte_pk0008.01_geoaddress.html)
[BR-PE-Recife/pk0010.01](http://addressforall.org/teste2/br-pe-recife_pk0010.01_nsvia.html)
[BR-PR-Cascavel/pk0011.01](http://addressforall.org/teste2/br-pr-cascavel_pk0011.01_nsvia.html)
[BR-PR-Pinhais/pk0014.01](http://addressforall.org/teste2/br-pr-pinhais_pk0014.01_nsvia.html)
[BR-RJ-Niteroi/pk0016.01](http://addressforall.org/teste2/br-rj-niteroi_pk0016.01_nsvia.html)
[BR-RJ-RioJaneiro/pk0078.02](http://addressforall.org/teste2/br-rj-riojaneiro_pk0078.02_block.html)
[BR-RS-CaxiasSul/pk0069.01](http://addressforall.org/teste2/br-rs-caxiassul_pk0069.01_block.html)
[BR-SC-Florianopolis/pk0053.01](http://addressforall.org/teste2/br-sc-florianopolis_pk0053.01_nsvia.html)
[BR-SC-Joinville/pk0035.01](http://addressforall.org/teste2/br-sc-joinville_pk0035.01_block.html)
[BR-SP-Campinas/pk0022.01](http://addressforall.org/teste2/br-sp-campinas_pk0022.01_geoaddress.html)
[BR-SP-Guarulhos/pk0081.01](http://addressforall.org/teste2/br-sp-guarulhos_pk0081.01_geoaddress.html)
[BR-SP-Piracicaba/pk0041.01](http://addressforall.org/teste2/br-sp-piracicaba_pk0041.01_block.html)
[BR-SP-SaoBernardoCampo/pk0030.01](http://addressforall.org/teste2/br-sp-saobernardocampo_pk0030.01_geoaddress.html)
[BR-SP-SaoPaulo/pk0033.01](http://addressforall.org/teste2/br-sp-saopaulo_pk0033.01_block.html)

**Comment by luisfelipebr** [comment]
@ppKrauss quando o download é inédito, podemos considerar os dados como inéditos, certo?

**Comment by ppKrauss** [comment]
> @ppKrauss quando o download é inédito, podemos considerar os dados como inéditos, certo?

Não sei se entendi,

* **Dado inédito**: aquele que ninguém tinha acesso público antes, mas com a publicação  AddressForAll passou a ter. Tipicamente dados doados por e-mail (teve um só caso até hoje que fomos buscar um DVD).

* **Dado não-inédito**: o contrário de *inédito*. Em geral se a prefeitura oferece Download já deixa de ser inédito automaticamente... A questão é se foi antes ou depois da AddressForAll publicar. Pode conferir em archive.org

... Um dia todos deixam de ser inéditos, então nosso objetivo aqui é classificar como "inédito" tudo aquilo que no dia que fizemos a primeira publicação online (atualmente o /teste2) era comprovadamente inédito.

-----

Apesar de muitos dados não serem inéditos, sempre bom lembrar dos **diferenciais dos dados da AddressForAll**, mesmo quando não são inéditos :
1. Segurança Jurídica: publicamos todas as evidências (de dados e de licença) e garantimos as licenças indicas.
2. Estabilidade: os dados são os mesmos por 20 anos, não se perdem, não se confundem e os mais atuais são diferenciáveis dos mais velhos, quando existe mais de uma versão do mesmo dado. Se você pagou IPTU ou registrou imóvel com relação ao cenário de uma certa data, esse cenário não é perdido.
4. Padronização semântica: não precisa filtrar e analisar, já fizemos isso e oferecemos um padrão de dados estável.
3. Curadoria: os conjuntos de dados que publicamos são prevaimente avaliados como consistentes e relevantes.

**Comment by ppKrauss** [comment]
@luisfelipebr resolvido?

**Comment by 0e1** [comment]
Dados publicados em https://addressforall.org/downloads/ com a tag `[unprecedented]` para indicar que são inéditos, conforme a definição dada. Considero que issue foi atendida.
