### ISSUE TITLE
Funções universais de cobertura

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#28]
<img align="right"  src="https://user-images.githubusercontent.com/1651447/182014559-3a79a568-b8cc-483a-b403-7c57e84b70a7.png">

O tema é tratado entre os matemáticos como [subpavimentação](https://en.wikipedia.org/wiki/Subpaving)... Dada uma geometria *X*, temos duas aproximações, *X⁻* e *X⁺*, tais que &nbsp;*X*⁻&nbsp;⊂ *X*&nbsp;⊂&nbsp;*X⁺*. 

Precisamos de duas funções neste projeto:

1. A **cobertura interior**, ou seja, *X⁻*, e portanto uma aproximação de subpavimentação conforme os limites de grade ou de número de células imposto. Na ilustração é a parte vermelha.

2. A **cobertura com borda**, ou seja, *X⁺*. Na ilustração a união da parte vermelha com a amarela, onde a parte amarela é a aproximação de borda.

Outra abordagem, a [Morfologia Matemática](https://en.wikipedia.org/wiki/Mathematical_morphology), trata sempre da aproximação de *X* como ponto de partida: *X⁺* é a sua **dilatação** e *X⁻* a sua **erosão**, mas existem centenas de maneiras diferentes para se erodir ou dilatar, ver [livro em portugues](https://www.ime.usp.br/~jb/articles/banon-barrera-bases-morfologia-matematica-analise-imagens-binarias.pdf).  No PostGIS temos  [ST_Buffer](https://postgis.net/docs/ST_Buffer.html) positivo e negativo como recurso para depois discretizar na grade, quando um controle métrico for necessário. 

## Implementação

Ver "region cover" (de fato esse é o nome mais popular para a funcionalidade) em [s2.sidewalklabs.com/regioncoverer](https://s2.sidewalklabs.com/regioncoverer/) ou [S2 Covering Examples](https://s2geometry.io/devguide/examples/coverings.html).

A **interseção** pode ser uma boa referência:

* **interseção da borda com grade fixa de maior resolução**: pode depois ser otimizada com substituição das células interiores por grades de menor resolução. Pode retornar a borda, o interior *X⁻* ou *X⁺*.  

* **interseção da borda com espeçura  fixa**:   tomando-se um buffer métrico da linha de borda podemos medir a área de interseção de modo a selecionar mais corretamente a resolução mais grosseira, minimizando a quantidade de células que comporá a aproximação de borda.

* **interseção com tamanhos variávies**: usar o número de células como parâmetro. A função buscaria a menor área de não-interseção, resultando em  *X⁺*.

**Comment by elpbatista** [comment]
Aquí está resuelto https://github.com/eLucidataLLC/mapbrick 

Es un proyecto en el que estuve trabajando hace dos años para convertir un contour obtenido a partir de una imagen de satélite a bloques de Lego. El código escrito totalmente en Node (Javascript) es extremadamente sencillo. Se trata de generar un grid y luego "recortar" la geometría superpuesta. En dependencia de la condición que se use para comparar se puede obtener la frontera o los bloques contenidos.

Aquí puede ver un ejemplo: [Monte Fuji](https://raw.githubusercontent.com/eLucidataLLC/mapbrick/8f76c39f59518ee9d67cf73b3054bc9c4e5a78a1/img/fuji.svg)

**Comment by ppKrauss** [comment]
> Aquí está resuelto https://github.com/eLucidataLLC/mapbrick

Muito bom! Podemos talvez juntar para formar um guia didático os algoritmos de grade... Neste [pg_pubLib-v1/docs/src-illustrative](https://github.com/AddressForAll/pg_pubLib-v1/tree/main/docs/src-illustrative) tentei mostrar como funciona o algoritmo de cobertura com códigos hierárquicos binários (bitstrings).

A partir dele pude implementar no PostGIS a [solução real para Geohashes](https://github.com/AddressForAll/pg_pubLib-v1/blob/main/docs/pgis-geohash.md).

**Comment by ppKrauss** [comment]
**MUDOU-SE** para https://wiki.addressforall.org/doc/Subpavimenta%C3%A7%C3%A3o
