### ISSUE TITLE
Criar projeto GGeohash

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#29]
É importante desmembrar ou simplesmente não trazer tudo para WS (WebService), visto que a temática é outra. Podemos manter tudo numa biblioteca só, Generalized-Geohash, ou quebrar em duas, uma só para grade e outra só para geocódigos (hcode). Os geocódigos nominais (prefixo de geocódigo postal) ficam cada qual na sua jurisdição.

Já podemos supor que em todos países a denominação "geocódigo científico" será associada à base16h e sua grade, sem outra opção... E que, quando usada, a base32 será relacionada apenas ao sistema  misto (nominal+grade) de geocódigo postal. 

Trazer para o novo projeto as respectivas PubLibs, que serão agora libs de um Schema, e demais libs:

* https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib05hcode-distrib.sql
* https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib05hcode-encdec.sql
* https://github.com/osm-codes/CO_new/blob/main/src/step01def-lib.sql

**Comment by 0e1** [comment]
Considero concluível esse processo. Reabrir a issue caso faltou algo.
