### ISSUE TITLE
Bugs de dados de cobertura de município e sua detecção

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#33]
Por exemplo esse buraco em [CO-AMA-Leticia](http://osm.codes/CO-AMA-Leticia): ainda são 26, pode acrescentar mais um que seria o X6Q.

![image](https://user-images.githubusercontent.com/1651447/185745334-7f18929e-5304-4ee2-bf17-3812cbbfc360.png)

Está **pendente o uso de ferramentas de validação**.

**Comment by 0e1** [comment]
Situação corrigida.

Sobre o uso de ferramenta de validação, continuar na https://github.com/osm-codes/WS/issues/32.
