### ISSUE TITLE
Resolução de geocodigos

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#36]
Usando a [Expansão do protocolo GeoURI](https://inde.gov.br/images/inde/poster3/Expans%C3%A3o%20do%20protocolo%20GeoURI.pdf). 
Por exemplo para a resolução de Geohash, https://osm.codes/geo:ghs:d2g69pmx  
mas precisa decidir se resolve em célula da grade postal ou se mantém em Geohash. O natural por hora seria grade postal, como já faz com Geo URI.

**Comment by ppKrauss** [comment]
Ver #44

**Comment by 0e1** [comment]
Consolidei em https://github.com/osm-codes/WS/issues/44.
