### ISSUE TITLE
Falta redirecionar códigos numéricos de município

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#39]
Por exemplo no Uruguai temos esse ponto, do geocódigo postal [UY-CO-ColoniaSacramento\~**4D8DM**](http://osm.codes/UY-CO-ColoniaSacramento~4D8DM), e o sistema já sabe que a cidade é código 400, então deveria valer  `UY-400~4D8DM`, mas [o link não funciona](http://osm.codes/UY-400~4D8DM).  <br/>
![image](https://user-images.githubusercontent.com/1651447/193484933-f39e2f7b-7285-4a3c-96e5-4e19fa83105a.png)

PS: o caso análogo em Bogotá funciona, https://osm.codes/CO-11001-Y88H2

**Comment by 0e1** [comment]
Corrigido.

Isso aconteceu por `UY-jurisd_local_id` não estar em [mvwjurisdiction_synonym](url). O commit adicionou esses sinônimos: https://github.com/digital-guard/preserv/commit/4bfa86e10a73198eb1dc615b78e0dffaa4afc508. Até o momento a politica tem sido adicionar esses sinônimos confome são oferecidos códigos postais. A politca poderia ser outra: adicionar os sinônimos do tipo `ISO-jurisd_local_id` que existirem na base de dados.
