### ISSUE TITLE
Mudando de /view para /postal

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#40]
Nas configurações NGINX, o destino default dos geocódigos nominais de jurisdições, é a **interface de geocódigo postal**. Ver em https://github.com/osm-codes/WS/blob/main/src/conf.nginx  a mudança de `/view` para `/postal`.

Os casos gerais e de grade são gerenciados pela grade científica, `/scientific`.

**Comment by 0e1** [comment]
Apenas ajustei para [view_lex](https://github.com/osm-codes/gridMap-draftPages/tree/main/view_lex) responder para o prefixo _urn_.
