### ISSUE TITLE
git-site no redirecionador de git

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#45]
Pendente passar para pro git em https://github.com/osm-codes/WS/blob/main/src/nginx/osm.codes 
e @crebollobr  **implementar HTTPS**.
 
---
Para contemplar casos como https://osm-codes.github.io/Sfc4q/ precisamos do `git-site.osm.codes`, por exemplo https://git-site.osm.codes/Sfc4q

```nginx
server {
        listen              80;
        listen              443 ssl;
        include /etc/nginx/ssl.conf;
        server_name git-site.osm.codes;
        location ~ ^/?.+ {
                rewrite
                  ^/?(.*)$
                  /$1
                  break;
                proxy_pass http://osm-codes.github.io;
        }                      
} # \server
```

**Comment by crebollobr** [comment]
Feito o certificado, apesar de erro 404 no site

**Comment by ppKrauss** [comment]
> Feito o certificado, apesar de erro 404 no site

Não entendi, reportar o erro. O link abaixo está funcionando:

https://git-site.osm.codes/Sfc4q

**Comment by 0e1** [comment]
Assunto resolvido, fechando a issue.
