### ISSUE TITLE
Não usar multiplos NGINX

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#47]
Tal como em `/var/gits/_a4a/WS/src/config.nginx` deve haver  um só `/var/gits/_osmc/WS/src/config.nginx`. Quem faz o controle de versões é o git, não o humano.

PS: **jamais** poluir ou desestruturar o *git master*, usar [*git branching* para o desenvolvimento](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging).

**Comment by 0e1** [comment]
Movi old e test para config. Idem para os arquivos no servidor.
