### ISSUE TITLE
Tratamento de jurisdições e NGINX enxuto

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/WS#50]
Levar as issues específicas para cada país, por exemplo https://github.com/osm-codes/gridMap-draftPages/issues/82  é exclusiva do Brasil.. Mas antes precisamos de NGINX enxuto como diretiva geral, e algum script de verificação de não-conflito. Ideal os scripts NGINX serem gerados por template Mustache e então o mesmo JSON que alimenta o Mustache-NGINX alimenta também um python de teste.

**_Dá issue https://github.com/osm-codes/BR_new/issues/11_:**

Definir regrexes em CSV ou JSON. As regexes podem ser de dois tipos: genérica-global (no WS), e específica por sobrescrita (no país).  

**Cada país precisa do eu próprio gerador de NGINX** a partir de CSV ou JSON (local!) que alimentará Mustaches.

**Comment by ppKrauss** [comment]
Em outra issue já comentamos também que o ideal é cada país ter seu `make_conf.yaml` para configuração do AFAcodes da jurisdição, independente de ter sido automatizada ou não, permite gerar a documentação automatizamente e oferecer maior transparência quanto à definição do AFAcode.

**Comment by 0e1** [comment]
Consolidei essa issue em https://github.com/osm-codes/WS/issues/48#issue-1751019711.
